<?php

use App\Pais;
use Illuminate\Database\Seeder;

class PaisSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $p1 = Pais::create(['descricao' => 'Afeganistão', 'codigo_bacen' => 132]);
        $p2 = Pais::create(['descricao' => 'Albânia, República da', 'codigo_bacen' => 175]);
        $p3 = Pais::create(['descricao' => 'Alemanha', 'codigo_bacen' => 230]);
        $p4 = Pais::create(['descricao' => 'Burkina Faso', 'codigo_bacen' => 310]);
        $p5 = Pais::create(['descricao' => 'Andorra', 'codigo_bacen' => 370]);
        $p6 = Pais::create(['descricao' => 'Angola', 'codigo_bacen' => 400]);
        $p7 = Pais::create(['descricao' => 'Anguilla', 'codigo_bacen' => 418]);
        $p8 = Pais::create(['descricao' => 'Antigua e Barbuda', 'codigo_bacen' => 434]);
        $p9 = Pais::create(['descricao' => 'Antilhas Holandesas', 'codigo_bacen' => 477]);
        $p10 = Pais::create(['descricao' => 'Arábia Saudita', 'codigo_bacen' => 531]);
        $p11 = Pais::create(['descricao' => 'Argélia', 'codigo_bacen' => 590]);
        $p12 = Pais::create(['descricao' => 'Argentina', 'codigo_bacen' => 639]);
        $p13 = Pais::create(['descricao' => 'Armênia, República da', 'codigo_bacen' => 647]);
        $p14 = Pais::create(['descricao' => 'Aruba', 'codigo_bacen' => 655]);
        $p15 = Pais::create(['descricao' => 'Austrália', 'codigo_bacen' => 698]);
        $p16 = Pais::create(['descricao' => 'Áustria', 'codigo_bacen' => 728]);
        $p17 = Pais::create(['descricao' => 'Azerbaijão, República do', 'codigo_bacen' => 736]);
        $p18 = Pais::create(['descricao' => 'Bahamas, Ilhas', 'codigo_bacen' => 779]);
        $p19 = Pais::create(['descricao' => 'Bahrein, Ilhas', 'codigo_bacen' => 809]);
        $p20 = Pais::create(['descricao' => 'Bangladesh', 'codigo_bacen' => 817]);
        $p21 = Pais::create(['descricao' => 'Barbados', 'codigo_bacen' => 833]);
        $p22 = Pais::create(['descricao' => 'Belarus', 'codigo_bacen' => 850]);
        $p23 = Pais::create(['descricao' => 'Bélgica', 'codigo_bacen' => 876]);
        $p24 = Pais::create(['descricao' => 'Belize', 'codigo_bacen' => 884]);
        $p25 = Pais::create(['descricao' => 'Bermudas', 'codigo_bacen' => 906]);
        $p26 = Pais::create(['descricao' => 'Mianmar (Birmânia', 'codigo_bacen' => 930]);
        $p27 = Pais::create(['descricao' => 'Bolívia', 'codigo_bacen' => 973]);
        $p28 = Pais::create(['descricao' => 'Bósnia-Herzegovina', 'codigo_bacen' => 981]);
        $p29 = Pais::create(['descricao' => 'Botsuana', 'codigo_bacen' => 1015]);
        $p30 = Pais::create(['descricao' => 'Brasil', 'codigo_bacen' => 1058]);
        $p31 = Pais::create(['descricao' => 'Brunei', 'codigo_bacen' => 1082]);
        $p32 = Pais::create(['descricao' => 'Bulgária, República da', 'codigo_bacen' => 1112]);
        $p33 = Pais::create(['descricao' => 'Burundi', 'codigo_bacen' => 1155]);
        $p34 = Pais::create(['descricao' => 'Butão', 'codigo_bacen' => 1198]);
        $p35 = Pais::create(['descricao' => 'Cabo Verde, República de', 'codigo_bacen' => 1279]);
        $p36 = Pais::create(['descricao' => 'Cayman, Ilhas', 'codigo_bacen' => 1376]);
        $p37 = Pais::create(['descricao' => 'Camboja', 'codigo_bacen' => 1414]);
        $p38 = Pais::create(['descricao' => 'Camarões', 'codigo_bacen' => 1457]);
        $p39 = Pais::create(['descricao' => 'Canadá', 'codigo_bacen' => 1490]);
        $p40 = Pais::create(['descricao' => 'Canal, Ilhas do (Jersey e Guernsey', 'codigo_bacen' => 1504]);
        $p41 = Pais::create(['descricao' => 'Canárias, Ilhas', 'codigo_bacen' => 1511]);
        $p42 = Pais::create(['descricao' => 'Cazaquistão, República do', 'codigo_bacen' => 1538]);
        $p43 = Pais::create(['descricao' => 'Catar', 'codigo_bacen' => 1546]);
        $p44 = Pais::create(['descricao' => 'Chile', 'codigo_bacen' => 1589]);
        $p45 = Pais::create(['descricao' => 'China, República Popular da', 'codigo_bacen' => 1600]);
        $p46 = Pais::create(['descricao' => 'Formosa (Taiwan', 'codigo_bacen' => 1619]);
        $p47 = Pais::create(['descricao' => 'Chipre', 'codigo_bacen' => 1635]);
        $p48 = Pais::create(['descricao' => 'Cocos (Keeling, Ilhas', 'codigo_bacen' => 1651]);
        $p49 = Pais::create(['descricao' => 'Colômbia', 'codigo_bacen' => 1694]);
        $p50 = Pais::create(['descricao' => 'Comores, Ilhas', 'codigo_bacen' => 1732]);
        $p51 = Pais::create(['descricao' => 'Congo, República do', 'codigo_bacen' => 1775]);
        $p52 = Pais::create(['descricao' => 'Cook, Ilhas', 'codigo_bacen' => 1830]);
        $p53 = Pais::create(['descricao' => 'Coréia, Rep. Pop. Democrática da', 'codigo_bacen' => 1872]);
        $p54 = Pais::create(['descricao' => 'Coréia, República da', 'codigo_bacen' => 1902]);
        $p55 = Pais::create(['descricao' => 'Costa do Marfim', 'codigo_bacen' => 1937]);
        $p56 = Pais::create(['descricao' => 'Croácia, República da', 'codigo_bacen' => 1953]);
        $p57 = Pais::create(['descricao' => 'Costa Rica', 'codigo_bacen' => 1961]);
        $p58 = Pais::create(['descricao' => 'Coveite', 'codigo_bacen' => 1988]);
        $p59 = Pais::create(['descricao' => 'Cuba', 'codigo_bacen' => 1996]);
        $p60 = Pais::create(['descricao' => 'Benin', 'codigo_bacen' => 2291]);
        $p61 = Pais::create(['descricao' => 'Dinamarca', 'codigo_bacen' => 2321]);
        $p62 = Pais::create(['descricao' => 'Dominica, Ilha', 'codigo_bacen' => 2356]);
        $p63 = Pais::create(['descricao' => 'Equador', 'codigo_bacen' => 2399]);
        $p64 = Pais::create(['descricao' => 'Egito', 'codigo_bacen' => 2402]);
        $p65 = Pais::create(['descricao' => 'Eritréia', 'codigo_bacen' => 2437]);
        $p66 = Pais::create(['descricao' => 'Emirados Árabes Unidos', 'codigo_bacen' => 2445]);
        $p67 = Pais::create(['descricao' => 'Espanha', 'codigo_bacen' => 2453]);
        $p68 = Pais::create(['descricao' => 'Eslovênia, República da', 'codigo_bacen' => 2461]);
        $p69 = Pais::create(['descricao' => 'Eslovaca, República', 'codigo_bacen' => 2470]);
        $p70 = Pais::create(['descricao' => 'Estados Unidos', 'codigo_bacen' => 2496]);
        $p71 = Pais::create(['descricao' => 'Estônia, República da', 'codigo_bacen' => 2518]);
        $p72 = Pais::create(['descricao' => 'Etiópia', 'codigo_bacen' => 2534]);
        $p73 = Pais::create(['descricao' => 'Falkland (Ilhas Malvinas', 'codigo_bacen' => 2550]);
        $p74 = Pais::create(['descricao' => 'Feroe, Ilhas', 'codigo_bacen' => 2593]);
        $p75 = Pais::create(['descricao' => 'Filipinas', 'codigo_bacen' => 2674]);
        $p76 = Pais::create(['descricao' => 'Finlândia', 'codigo_bacen' => 2712]);
        $p77 = Pais::create(['descricao' => 'França', 'codigo_bacen' => 2755]);
        $p78 = Pais::create(['descricao' => 'Gabão', 'codigo_bacen' => 2810]);
        $p79 = Pais::create(['descricao' => 'Gâmbia', 'codigo_bacen' => 2852]);
        $p80 = Pais::create(['descricao' => 'Gana', 'codigo_bacen' => 2895]);
        $p81 = Pais::create(['descricao' => 'Geórgia, República da', 'codigo_bacen' => 2917]);
        $p82 = Pais::create(['descricao' => 'Gibraltar', 'codigo_bacen' => 2933]);
        $p83 = Pais::create(['descricao' => 'Granada', 'codigo_bacen' => 2976]);
        $p84 = Pais::create(['descricao' => 'Grécia', 'codigo_bacen' => 3018]);
        $p85 = Pais::create(['descricao' => 'Groenlândia', 'codigo_bacen' => 3050]);
        $p86 = Pais::create(['descricao' => 'Guadalupe', 'codigo_bacen' => 3093]);
        $p87 = Pais::create(['descricao' => 'Guam', 'codigo_bacen' => 3131]);
        $p88 = Pais::create(['descricao' => 'Guatemala', 'codigo_bacen' => 3174]);
        $p89 = Pais::create(['descricao' => 'Guiana Francesa', 'codigo_bacen' => 3255]);
        $p90 = Pais::create(['descricao' => 'Guiné', 'codigo_bacen' => 3298]);
        $p91 = Pais::create(['descricao' => 'Guiné-Equatorial', 'codigo_bacen' => 3310]);
        $p92 = Pais::create(['descricao' => 'Guiné-Bissau', 'codigo_bacen' => 3344]);
        $p93 = Pais::create(['descricao' => 'Guiana', 'codigo_bacen' => 3379]);
        $p94 = Pais::create(['descricao' => 'Haiti', 'codigo_bacen' => 3417]);
        $p95 = Pais::create(['descricao' => 'Honduras', 'codigo_bacen' => 3450]);
        $p96 = Pais::create(['descricao' => 'Hong Kong, Região Adm. Especial', 'codigo_bacen' => 3514]);
        $p97 = Pais::create(['descricao' => 'Hungria, República da', 'codigo_bacen' => 3557]);
        $p98 = Pais::create(['descricao' => 'Iêmen', 'codigo_bacen' => 3573]);
        $p99 = Pais::create(['descricao' => 'Man, Ilhas', 'codigo_bacen' => 3595]);
        $p100 = Pais::create(['descricao' => 'Índia', 'codigo_bacen' => 3611]);
        $p101 = Pais::create(['descricao' => 'Indonésia', 'codigo_bacen' => 3654]);
        $p102 = Pais::create(['descricao' => 'Iraque', 'codigo_bacen' => 3697]);
        $p103 = Pais::create(['descricao' => 'Irã, República Islâmica do', 'codigo_bacen' => 3727]);
        $p104 = Pais::create(['descricao' => 'Irlanda', 'codigo_bacen' => 3751]);
        $p105 = Pais::create(['descricao' => 'Islândia', 'codigo_bacen' => 3794]);
        $p106 = Pais::create(['descricao' => 'Israel', 'codigo_bacen' => 3832]);
        $p107 = Pais::create(['descricao' => 'Itália', 'codigo_bacen' => 3867]);
        $p108 = Pais::create(['descricao' => 'Iugoslávia, República Fed. da', 'codigo_bacen' => 3883]);
        $p109 = Pais::create(['descricao' => 'Jamaica', 'codigo_bacen' => 3913]);
        $p110 = Pais::create(['descricao' => 'Johnston, Ilhas', 'codigo_bacen' => 3964]);
        $p111 = Pais::create(['descricao' => 'Japão', 'codigo_bacen' => 3999]);
        $p112 = Pais::create(['descricao' => 'Jordânia', 'codigo_bacen' => 4030]);
        $p113 = Pais::create(['descricao' => 'Kiribati', 'codigo_bacen' => 4111]);
        $p114 = Pais::create(['descricao' => 'Laos, Rep. Pop. Democrática do', 'codigo_bacen' => 4200]);
        $p115 = Pais::create(['descricao' => 'Lebuan', 'codigo_bacen' => 4235]);
        $p116 = Pais::create(['descricao' => 'Lesoto', 'codigo_bacen' => 4260]);
        $p117 = Pais::create(['descricao' => 'Letônia, República da', 'codigo_bacen' => 4278]);
        $p118 = Pais::create(['descricao' => 'Líbano', 'codigo_bacen' => 4316]);
        $p119 = Pais::create(['descricao' => 'Libéria', 'codigo_bacen' => 4340]);
        $p120 = Pais::create(['descricao' => 'Líbia', 'codigo_bacen' => 4383]);
        $p121 = Pais::create(['descricao' => 'Liechtenstein', 'codigo_bacen' => 4405]);
        $p122 = Pais::create(['descricao' => 'Lituânia, República da', 'codigo_bacen' => 4421]);
        $p123 = Pais::create(['descricao' => 'Luxemburgo', 'codigo_bacen' => 4456]);
        $p124 = Pais::create(['descricao' => 'Macau', 'codigo_bacen' => 4472]);
        $p125 = Pais::create(['descricao' => 'Macedônia', 'codigo_bacen' => 4499]);
        $p126 = Pais::create(['descricao' => 'Madagascar', 'codigo_bacen' => 4502]);
        $p127 = Pais::create(['descricao' => 'Madeira, Ilha da', 'codigo_bacen' => 4525]);
        $p128 = Pais::create(['descricao' => 'Malásia', 'codigo_bacen' => 4553]);
        $p129 = Pais::create(['descricao' => 'Malavi', 'codigo_bacen' => 4588]);
        $p130 = Pais::create(['descricao' => 'Maldivas', 'codigo_bacen' => 4618]);
        $p131 = Pais::create(['descricao' => 'Máli', 'codigo_bacen' => 4642]);
        $p132 = Pais::create(['descricao' => 'Malta', 'codigo_bacen' => 4677]);
        $p133 = Pais::create(['descricao' => 'Marianas do Norte', 'codigo_bacen' => 4723]);
        $p134 = Pais::create(['descricao' => 'Marrocos', 'codigo_bacen' => 4740]);
        $p135 = Pais::create(['descricao' => 'Marshall, Ilhas', 'codigo_bacen' => 4766]);
        $p136 = Pais::create(['descricao' => 'Martinica', 'codigo_bacen' => 4774]);
        $p137 = Pais::create(['descricao' => 'Maurício', 'codigo_bacen' => 4855]);
        $p138 = Pais::create(['descricao' => 'Mauritânia', 'codigo_bacen' => 4880]);
        $p139 = Pais::create(['descricao' => 'Midway, Ilhas', 'codigo_bacen' => 4901]);
        $p140 = Pais::create(['descricao' => 'México', 'codigo_bacen' => 4936]);
        $p141 = Pais::create(['descricao' => 'Moldávia, República da', 'codigo_bacen' => 4944]);
        $p142 = Pais::create(['descricao' => 'Mônaco', 'codigo_bacen' => 4952]);
        $p143 = Pais::create(['descricao' => 'Mongólia', 'codigo_bacen' => 4979]);
        $p144 = Pais::create(['descricao' => 'Micronésia', 'codigo_bacen' => 4995]);
        $p145 = Pais::create(['descricao' => 'Montserrat, Ilhas', 'codigo_bacen' => 5010]);
        $p146 = Pais::create(['descricao' => 'Moçambique', 'codigo_bacen' => 5053]);
        $p147 = Pais::create(['descricao' => 'Namíbia', 'codigo_bacen' => 5070]);
        $p148 = Pais::create(['descricao' => 'Nauru', 'codigo_bacen' => 5088]);
        $p149 = Pais::create(['descricao' => 'Christmas, Ilha (Navidad', 'codigo_bacen' => 5118]);
        $p150 = Pais::create(['descricao' => 'Nepal', 'codigo_bacen' => 5177]);
        $p151 = Pais::create(['descricao' => 'Nicarágua', 'codigo_bacen' => 5215]);
        $p152 = Pais::create(['descricao' => 'Niger', 'codigo_bacen' => 5258]);
        $p153 = Pais::create(['descricao' => 'Nigéria', 'codigo_bacen' => 5282]);
        $p154 = Pais::create(['descricao' => 'Niue, Ilha', 'codigo_bacen' => 5312]);
        $p155 = Pais::create(['descricao' => 'Norfolk, Ilha', 'codigo_bacen' => 5355]);
        $p156 = Pais::create(['descricao' => 'Noruega', 'codigo_bacen' => 5380]);
        $p157 = Pais::create(['descricao' => 'Nova Caledônia', 'codigo_bacen' => 5428]);
        $p158 = Pais::create(['descricao' => 'Papua Nova Guiné', 'codigo_bacen' => 5452]);
        $p159 = Pais::create(['descricao' => 'Nova Zelândia', 'codigo_bacen' => 5487]);
        $p160 = Pais::create(['descricao' => 'Vanuatu', 'codigo_bacen' => 5517]);
        $p161 = Pais::create(['descricao' => 'Omã', 'codigo_bacen' => 5568]);
        $p162 = Pais::create(['descricao' => 'Holanda (Países Baixos', 'codigo_bacen' => 5738]);
        $p163 = Pais::create(['descricao' => 'Países Baixos (Holanda', 'codigo_bacen' => 5738]);
        $p164 = Pais::create(['descricao' => 'Palau', 'codigo_bacen' => 5754]);
        $p165 = Pais::create(['descricao' => 'Paquistão', 'codigo_bacen' => 5762]);
        $p166 = Pais::create(['descricao' => 'Panamá', 'codigo_bacen' => 5800]);
        $p167 = Pais::create(['descricao' => 'Paraguai', 'codigo_bacen' => 5860]);
        $p168 = Pais::create(['descricao' => 'Peru', 'codigo_bacen' => 5894]);
        $p169 = Pais::create(['descricao' => 'Pitcairn, Ilha', 'codigo_bacen' => 5932]);
        $p170 = Pais::create(['descricao' => 'Polinésia Francesa', 'codigo_bacen' => 5991]);
        $p171 = Pais::create(['descricao' => 'Polônia, República da', 'codigo_bacen' => 6033]);
        $p172 = Pais::create(['descricao' => 'Portugal', 'codigo_bacen' => 6076]);
        $p173 = Pais::create(['descricao' => 'Porto Rico', 'codigo_bacen' => 6114]);
        $p174 = Pais::create(['descricao' => 'Quênia', 'codigo_bacen' => 6238]);
        $p175 = Pais::create(['descricao' => 'Quirguiz, República', 'codigo_bacen' => 6254]);
        $p176 = Pais::create(['descricao' => 'Escócia', 'codigo_bacen' => 6289]);
        $p177 = Pais::create(['descricao' => 'Gales, País de', 'codigo_bacen' => 6289]);
        $p178 = Pais::create(['descricao' => 'Grã-Bretanha', 'codigo_bacen' => 6289]);
        $p179 = Pais::create(['descricao' => 'Inglaterra', 'codigo_bacen' => 6289]);
        $p180 = Pais::create(['descricao' => 'Irlanda do Norte', 'codigo_bacen' => 6289]);
        $p181 = Pais::create(['descricao' => 'Reino Unido', 'codigo_bacen' => 6289]);
        $p182 = Pais::create(['descricao' => 'República Centro-Africana', 'codigo_bacen' => 6408]);
        $p183 = Pais::create(['descricao' => 'República Dominicana', 'codigo_bacen' => 6475]);
        $p184 = Pais::create(['descricao' => 'Reunião, Ilha', 'codigo_bacen' => 6602]);
        $p185 = Pais::create(['descricao' => 'Zimbábue', 'codigo_bacen' => 6653]);
        $p186 = Pais::create(['descricao' => 'Romênia', 'codigo_bacen' => 6700]);
        $p187 = Pais::create(['descricao' => 'Ruanda', 'codigo_bacen' => 6750]);
        $p188 = Pais::create(['descricao' => 'Rússia', 'codigo_bacen' => 6769]);
        $p189 = Pais::create(['descricao' => 'Salomão, Ilhas', 'codigo_bacen' => 6777]);
        $p190 = Pais::create(['descricao' => 'Saara Ocidental', 'codigo_bacen' => 6858]);
        $p191 = Pais::create(['descricao' => 'El Salvador', 'codigo_bacen' => 6874]);
        $p192 = Pais::create(['descricao' => 'Samoa', 'codigo_bacen' => 6904]);
        $p193 = Pais::create(['descricao' => 'Samoa Americana', 'codigo_bacen' => 6912]);
        $p194 = Pais::create(['descricao' => 'São Cristóvão e Neves', 'codigo_bacen' => 6955]);
        $p195 = Pais::create(['descricao' => 'San Marino', 'codigo_bacen' => 6971]);
        $p196 = Pais::create(['descricao' => 'São Pedro e Miquelon', 'codigo_bacen' => 7005]);
        $p197 = Pais::create(['descricao' => 'São Vicente e Granadinas', 'codigo_bacen' => 7056]);
        $p198 = Pais::create(['descricao' => 'Santa Helena', 'codigo_bacen' => 7102]);
        $p199 = Pais::create(['descricao' => 'Santa Lúcia', 'codigo_bacen' => 7153]);
        $p200 = Pais::create(['descricao' => 'São Tomé e Príncipe, Ilhas', 'codigo_bacen' => 7200]);
        $p201 = Pais::create(['descricao' => 'Senegal', 'codigo_bacen' => 7285]);
        $p202 = Pais::create(['descricao' => 'Seychelles', 'codigo_bacen' => 7315]);
        $p203 = Pais::create(['descricao' => 'Serra Leoa', 'codigo_bacen' => 7358]);
        $p204 = Pais::create(['descricao' => 'Cingapura', 'codigo_bacen' => 7412]);
        $p205 = Pais::create(['descricao' => 'Síria, República Árabe da', 'codigo_bacen' => 7447]);
        $p206 = Pais::create(['descricao' => 'Somália', 'codigo_bacen' => 7480]);
        $p207 = Pais::create(['descricao' => 'Sri Lanka', 'codigo_bacen' => 7501]);
        $p208 = Pais::create(['descricao' => 'Suazilândia', 'codigo_bacen' => 7544]);
        $p209 = Pais::create(['descricao' => 'África do Sul', 'codigo_bacen' => 7560]);
        $p210 = Pais::create(['descricao' => 'Sudão', 'codigo_bacen' => 7595]);
        $p211 = Pais::create(['descricao' => 'Suécia', 'codigo_bacen' => 7641]);
        $p212 = Pais::create(['descricao' => 'Suíça', 'codigo_bacen' => 7676]);
        $p213 = Pais::create(['descricao' => 'Suriname', 'codigo_bacen' => 7706]);
        $p214 = Pais::create(['descricao' => 'Tadjiquistão', 'codigo_bacen' => 7722]);
        $p215 = Pais::create(['descricao' => 'Tailândia', 'codigo_bacen' => 7765]);
        $p216 = Pais::create(['descricao' => 'Tanzânia, República Unida da', 'codigo_bacen' => 7803]);
        $p217 = Pais::create(['descricao' => 'Território Britânico Oc. Índico', 'codigo_bacen' => 7820]);
        $p218 = Pais::create(['descricao' => 'Djibuti', 'codigo_bacen' => 7838]);
        $p219 = Pais::create(['descricao' => 'Chade', 'codigo_bacen' => 7889]);
        $p220 = Pais::create(['descricao' => 'Tcheca, República', 'codigo_bacen' => 7919]);
        $p221 = Pais::create(['descricao' => 'Timor Leste', 'codigo_bacen' => 7951]);
        $p222 = Pais::create(['descricao' => 'Togo', 'codigo_bacen' => 8001]);
        $p223 = Pais::create(['descricao' => 'Toquelau, Ilhas', 'codigo_bacen' => 8052]);
        $p224 = Pais::create(['descricao' => 'Tonga', 'codigo_bacen' => 8109]);
        $p225 = Pais::create(['descricao' => 'Trinidad e Tobago', 'codigo_bacen' => 8150]);
        $p226 = Pais::create(['descricao' => 'Tunísia', 'codigo_bacen' => 8206]);
        $p227 = Pais::create(['descricao' => 'Turcas e Caicos, Ilhas', 'codigo_bacen' => 8230]);
        $p228 = Pais::create(['descricao' => 'Turcomenistão, República do', 'codigo_bacen' => 8249]);
        $p229 = Pais::create(['descricao' => 'Turquia', 'codigo_bacen' => 8273]);
        $p230 = Pais::create(['descricao' => 'Tuvalu', 'codigo_bacen' => 8281]);
        $p231 = Pais::create(['descricao' => 'Ucrânia', 'codigo_bacen' => 8311]);
        $p232 = Pais::create(['descricao' => 'Uganda', 'codigo_bacen' => 8338]);
        $p233 = Pais::create(['descricao' => 'Uruguai', 'codigo_bacen' => 8451]);
        $p234 = Pais::create(['descricao' => 'Uzbequistão, República do', 'codigo_bacen' => 8478]);
        $p235 = Pais::create(['descricao' => 'Vaticano, Estado da Cidade do', 'codigo_bacen' => 8486]);
        $p236 = Pais::create(['descricao' => 'Venezuela', 'codigo_bacen' => 8508]);
        $p237 = Pais::create(['descricao' => 'Vietnã', 'codigo_bacen' => 8583]);
        $p238 = Pais::create(['descricao' => 'Virgens, Ilhas (Britânicas', 'codigo_bacen' => 8630]);
        $p239 = Pais::create(['descricao' => 'Virgens, Ilhas (E.U.A.', 'codigo_bacen' => 8664]);
        $p240 = Pais::create(['descricao' => 'Fiji', 'codigo_bacen' => 8702]);
        $p241 = Pais::create(['descricao' => 'Wake, Ilha', 'codigo_bacen' => 8737]);
        $p242 = Pais::create(['descricao' => 'Wallis e Futuna, Ilhas', 'codigo_bacen' => 8753]);
        $p243 = Pais::create(['descricao' => 'Congo, República Democrática do', 'codigo_bacen' => 8885]);
        $p244 = Pais::create(['descricao' => 'Zâmbia', 'codigo_bacen' => 8907]);
        $p245 = Pais::create(['descricao' => 'Zona do Canal do Panamá', 'codigo_bacen' => 8958]);

    }
}
