<?php

use App\Pais;
use Illuminate\Database\Seeder;

class PaisSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::update(DB::raw('truncate table paises restart identity cascade'));

        Pais::create(['descricao' => 'Afeganistão', 'codigo_bacen' => 132]);
        Pais::create(['descricao' => 'Albânia, República da', 'codigo_bacen' => 175]);
        Pais::create(['descricao' => 'Alemanha', 'codigo_bacen' => 230]);
        Pais::create(['descricao' => 'Burkina Faso', 'codigo_bacen' => 310]);
        Pais::create(['descricao' => 'Andorra', 'codigo_bacen' => 370]);
        Pais::create(['descricao' => 'Angola', 'codigo_bacen' => 400]);
        Pais::create(['descricao' => 'Anguilla', 'codigo_bacen' => 418]);
        Pais::create(['descricao' => 'Antigua e Barbuda', 'codigo_bacen' => 434]);
        Pais::create(['descricao' => 'Antilhas Holandesas', 'codigo_bacen' => 477]);
        Pais::create(['descricao' => 'Arábia Saudita', 'codigo_bacen' => 531]);
        Pais::create(['descricao' => 'Argélia', 'codigo_bacen' => 590]);
        Pais::create(['descricao' => 'Argentina', 'codigo_bacen' => 639]);
        Pais::create(['descricao' => 'Armênia, República da', 'codigo_bacen' => 647]);
        Pais::create(['descricao' => 'Aruba', 'codigo_bacen' => 655]);
        Pais::create(['descricao' => 'Austrália', 'codigo_bacen' => 698]);
        Pais::create(['descricao' => 'Áustria', 'codigo_bacen' => 728]);
        Pais::create(['descricao' => 'Azerbaijão, República do', 'codigo_bacen' => 736]);
        Pais::create(['descricao' => 'Bahamas, Ilhas', 'codigo_bacen' => 779]);
        Pais::create(['descricao' => 'Bahrein, Ilhas', 'codigo_bacen' => 809]);
        Pais::create(['descricao' => 'Bangladesh', 'codigo_bacen' => 817]);
        Pais::create(['descricao' => 'Barbados', 'codigo_bacen' => 833]);
        Pais::create(['descricao' => 'Belarus', 'codigo_bacen' => 850]);
        Pais::create(['descricao' => 'Bélgica', 'codigo_bacen' => 876]);
        Pais::create(['descricao' => 'Belize', 'codigo_bacen' => 884]);
        Pais::create(['descricao' => 'Bermudas', 'codigo_bacen' => 906]);
        Pais::create(['descricao' => 'Mianmar (Birmânia', 'codigo_bacen' => 930]);
        Pais::create(['descricao' => 'Bolívia', 'codigo_bacen' => 973]);
        Pais::create(['descricao' => 'Bósnia-Herzegovina', 'codigo_bacen' => 981]);
        Pais::create(['descricao' => 'Botsuana', 'codigo_bacen' => 1015]);
        Pais::create(['descricao' => 'Brasil', 'codigo_bacen' => 1058]);
        Pais::create(['descricao' => 'Brunei', 'codigo_bacen' => 1082]);
        Pais::create(['descricao' => 'Bulgária, República da', 'codigo_bacen' => 1112]);
        Pais::create(['descricao' => 'Burundi', 'codigo_bacen' => 1155]);
        Pais::create(['descricao' => 'Butão', 'codigo_bacen' => 1198]);
        Pais::create(['descricao' => 'Cabo Verde, República de', 'codigo_bacen' => 1279]);
        Pais::create(['descricao' => 'Cayman, Ilhas', 'codigo_bacen' => 1376]);
        Pais::create(['descricao' => 'Camboja', 'codigo_bacen' => 1414]);
        Pais::create(['descricao' => 'Camarões', 'codigo_bacen' => 1457]);
        Pais::create(['descricao' => 'Canadá', 'codigo_bacen' => 1490]);
        Pais::create(['descricao' => 'Canal, Ilhas do (Jersey e Guernsey', 'codigo_bacen' => 1504]);
        Pais::create(['descricao' => 'Canárias, Ilhas', 'codigo_bacen' => 1511]);
        Pais::create(['descricao' => 'Cazaquistão, República do', 'codigo_bacen' => 1538]);
        Pais::create(['descricao' => 'Catar', 'codigo_bacen' => 1546]);
        Pais::create(['descricao' => 'Chile', 'codigo_bacen' => 1589]);
        Pais::create(['descricao' => 'China, República Popular da', 'codigo_bacen' => 1600]);
        Pais::create(['descricao' => 'Formosa (Taiwan', 'codigo_bacen' => 1619]);
        Pais::create(['descricao' => 'Chipre', 'codigo_bacen' => 1635]);
        Pais::create(['descricao' => 'Cocos (Keeling, Ilhas', 'codigo_bacen' => 1651]);
        Pais::create(['descricao' => 'Colômbia', 'codigo_bacen' => 1694]);
        Pais::create(['descricao' => 'Comores, Ilhas', 'codigo_bacen' => 1732]);
        Pais::create(['descricao' => 'Congo, República do', 'codigo_bacen' => 1775]);
        Pais::create(['descricao' => 'Cook, Ilhas', 'codigo_bacen' => 1830]);
        Pais::create(['descricao' => 'Coréia, Rep. Pop. Democrática da', 'codigo_bacen' => 1872]);
        Pais::create(['descricao' => 'Coréia, República da', 'codigo_bacen' => 1902]);
        Pais::create(['descricao' => 'Costa do Marfim', 'codigo_bacen' => 1937]);
        Pais::create(['descricao' => 'Croácia, República da', 'codigo_bacen' => 1953]);
        Pais::create(['descricao' => 'Costa Rica', 'codigo_bacen' => 1961]);
        Pais::create(['descricao' => 'Coveite', 'codigo_bacen' => 1988]);
        Pais::create(['descricao' => 'Cuba', 'codigo_bacen' => 1996]);
        Pais::create(['descricao' => 'Benin', 'codigo_bacen' => 2291]);
        Pais::create(['descricao' => 'Dinamarca', 'codigo_bacen' => 2321]);
        Pais::create(['descricao' => 'Dominica, Ilha', 'codigo_bacen' => 2356]);
        Pais::create(['descricao' => 'Equador', 'codigo_bacen' => 2399]);
        Pais::create(['descricao' => 'Egito', 'codigo_bacen' => 2402]);
        Pais::create(['descricao' => 'Eritréia', 'codigo_bacen' => 2437]);
        Pais::create(['descricao' => 'Emirados Árabes Unidos', 'codigo_bacen' => 2445]);
        Pais::create(['descricao' => 'Espanha', 'codigo_bacen' => 2453]);
        Pais::create(['descricao' => 'Eslovênia, República da', 'codigo_bacen' => 2461]);
        Pais::create(['descricao' => 'Eslovaca, República', 'codigo_bacen' => 2470]);
        Pais::create(['descricao' => 'Estados Unidos', 'codigo_bacen' => 2496]);
        Pais::create(['descricao' => 'Estônia, República da', 'codigo_bacen' => 2518]);
        Pais::create(['descricao' => 'Etiópia', 'codigo_bacen' => 2534]);
        Pais::create(['descricao' => 'Falkland (Ilhas Malvinas', 'codigo_bacen' => 2550]);
        Pais::create(['descricao' => 'Feroe, Ilhas', 'codigo_bacen' => 2593]);
        Pais::create(['descricao' => 'Filipinas', 'codigo_bacen' => 2674]);
        Pais::create(['descricao' => 'Finlândia', 'codigo_bacen' => 2712]);
        Pais::create(['descricao' => 'França', 'codigo_bacen' => 2755]);
        Pais::create(['descricao' => 'Gabão', 'codigo_bacen' => 2810]);
        Pais::create(['descricao' => 'Gâmbia', 'codigo_bacen' => 2852]);
        Pais::create(['descricao' => 'Gana', 'codigo_bacen' => 2895]);
        Pais::create(['descricao' => 'Geórgia, República da', 'codigo_bacen' => 2917]);
        Pais::create(['descricao' => 'Gibraltar', 'codigo_bacen' => 2933]);
        Pais::create(['descricao' => 'Granada', 'codigo_bacen' => 2976]);
        Pais::create(['descricao' => 'Grécia', 'codigo_bacen' => 3018]);
        Pais::create(['descricao' => 'Groenlândia', 'codigo_bacen' => 3050]);
        Pais::create(['descricao' => 'Guadalupe', 'codigo_bacen' => 3093]);
        Pais::create(['descricao' => 'Guam', 'codigo_bacen' => 3131]);
        Pais::create(['descricao' => 'Guatemala', 'codigo_bacen' => 3174]);
        Pais::create(['descricao' => 'Guiana Francesa', 'codigo_bacen' => 3255]);
        Pais::create(['descricao' => 'Guiné', 'codigo_bacen' => 3298]);
        Pais::create(['descricao' => 'Guiné-Equatorial', 'codigo_bacen' => 3310]);
        Pais::create(['descricao' => 'Guiné-Bissau', 'codigo_bacen' => 3344]);
        Pais::create(['descricao' => 'Guiana', 'codigo_bacen' => 3379]);
        Pais::create(['descricao' => 'Haiti', 'codigo_bacen' => 3417]);
        Pais::create(['descricao' => 'Honduras', 'codigo_bacen' => 3450]);
        Pais::create(['descricao' => 'Hong Kong, Região Adm. Especial', 'codigo_bacen' => 3514]);
        Pais::create(['descricao' => 'Hungria, República da', 'codigo_bacen' => 3557]);
        Pais::create(['descricao' => 'Iêmen', 'codigo_bacen' => 3573]);
        Pais::create(['descricao' => 'Man, Ilhas', 'codigo_bacen' => 3595]);
        Pais::create(['descricao' => 'Índia', 'codigo_bacen' => 3611]);
        Pais::create(['descricao' => 'Indonésia', 'codigo_bacen' => 3654]);
        Pais::create(['descricao' => 'Iraque', 'codigo_bacen' => 3697]);
        Pais::create(['descricao' => 'Irã, República Islâmica do', 'codigo_bacen' => 3727]);
        Pais::create(['descricao' => 'Irlanda', 'codigo_bacen' => 3751]);
        Pais::create(['descricao' => 'Islândia', 'codigo_bacen' => 3794]);
        Pais::create(['descricao' => 'Israel', 'codigo_bacen' => 3832]);
        Pais::create(['descricao' => 'Itália', 'codigo_bacen' => 3867]);
        Pais::create(['descricao' => 'Iugoslávia, República Fed. da', 'codigo_bacen' => 3883]);
        Pais::create(['descricao' => 'Jamaica', 'codigo_bacen' => 3913]);
        Pais::create(['descricao' => 'Johnston, Ilhas', 'codigo_bacen' => 3964]);
        Pais::create(['descricao' => 'Japão', 'codigo_bacen' => 3999]);
        Pais::create(['descricao' => 'Jordânia', 'codigo_bacen' => 4030]);
        Pais::create(['descricao' => 'Kiribati', 'codigo_bacen' => 4111]);
        Pais::create(['descricao' => 'Laos, Rep. Pop. Democrática do', 'codigo_bacen' => 4200]);
        Pais::create(['descricao' => 'Lebuan', 'codigo_bacen' => 4235]);
        Pais::create(['descricao' => 'Lesoto', 'codigo_bacen' => 4260]);
        Pais::create(['descricao' => 'Letônia, República da', 'codigo_bacen' => 4278]);
        Pais::create(['descricao' => 'Líbano', 'codigo_bacen' => 4316]);
        Pais::create(['descricao' => 'Libéria', 'codigo_bacen' => 4340]);
        Pais::create(['descricao' => 'Líbia', 'codigo_bacen' => 4383]);
        Pais::create(['descricao' => 'Liechtenstein', 'codigo_bacen' => 4405]);
        Pais::create(['descricao' => 'Lituânia, República da', 'codigo_bacen' => 4421]);
        Pais::create(['descricao' => 'Luxemburgo', 'codigo_bacen' => 4456]);
        Pais::create(['descricao' => 'Macau', 'codigo_bacen' => 4472]);
        Pais::create(['descricao' => 'Macedônia', 'codigo_bacen' => 4499]);
        Pais::create(['descricao' => 'Madagascar', 'codigo_bacen' => 4502]);
        Pais::create(['descricao' => 'Madeira, Ilha da', 'codigo_bacen' => 4525]);
        Pais::create(['descricao' => 'Malásia', 'codigo_bacen' => 4553]);
        Pais::create(['descricao' => 'Malavi', 'codigo_bacen' => 4588]);
        Pais::create(['descricao' => 'Maldivas', 'codigo_bacen' => 4618]);
        Pais::create(['descricao' => 'Máli', 'codigo_bacen' => 4642]);
        Pais::create(['descricao' => 'Malta', 'codigo_bacen' => 4677]);
        Pais::create(['descricao' => 'Marianas do Norte', 'codigo_bacen' => 4723]);
        Pais::create(['descricao' => 'Marrocos', 'codigo_bacen' => 4740]);
        Pais::create(['descricao' => 'Marshall, Ilhas', 'codigo_bacen' => 4766]);
        Pais::create(['descricao' => 'Martinica', 'codigo_bacen' => 4774]);
        Pais::create(['descricao' => 'Maurício', 'codigo_bacen' => 4855]);
        Pais::create(['descricao' => 'Mauritânia', 'codigo_bacen' => 4880]);
        Pais::create(['descricao' => 'Midway, Ilhas', 'codigo_bacen' => 4901]);
        Pais::create(['descricao' => 'México', 'codigo_bacen' => 4936]);
        Pais::create(['descricao' => 'Moldávia, República da', 'codigo_bacen' => 4944]);
        Pais::create(['descricao' => 'Mônaco', 'codigo_bacen' => 4952]);
        Pais::create(['descricao' => 'Mongólia', 'codigo_bacen' => 4979]);
        Pais::create(['descricao' => 'Micronésia', 'codigo_bacen' => 4995]);
        Pais::create(['descricao' => 'Montserrat, Ilhas', 'codigo_bacen' => 5010]);
        Pais::create(['descricao' => 'Moçambique', 'codigo_bacen' => 5053]);
        Pais::create(['descricao' => 'Namíbia', 'codigo_bacen' => 5070]);
        Pais::create(['descricao' => 'Nauru', 'codigo_bacen' => 5088]);
        Pais::create(['descricao' => 'Christmas, Ilha (Navidad', 'codigo_bacen' => 5118]);
        Pais::create(['descricao' => 'Nepal', 'codigo_bacen' => 5177]);
        Pais::create(['descricao' => 'Nicarágua', 'codigo_bacen' => 5215]);
        Pais::create(['descricao' => 'Niger', 'codigo_bacen' => 5258]);
        Pais::create(['descricao' => 'Nigéria', 'codigo_bacen' => 5282]);
        Pais::create(['descricao' => 'Niue, Ilha', 'codigo_bacen' => 5312]);
        Pais::create(['descricao' => 'Norfolk, Ilha', 'codigo_bacen' => 5355]);
        Pais::create(['descricao' => 'Noruega', 'codigo_bacen' => 5380]);
        Pais::create(['descricao' => 'Nova Caledônia', 'codigo_bacen' => 5428]);
        Pais::create(['descricao' => 'Papua Nova Guiné', 'codigo_bacen' => 5452]);
        Pais::create(['descricao' => 'Nova Zelândia', 'codigo_bacen' => 5487]);
        Pais::create(['descricao' => 'Vanuatu', 'codigo_bacen' => 5517]);
        Pais::create(['descricao' => 'Omã', 'codigo_bacen' => 5568]);
        Pais::create(['descricao' => 'Holanda (Países Baixos', 'codigo_bacen' => 5738]);
        Pais::create(['descricao' => 'Países Baixos (Holanda', 'codigo_bacen' => 5738]);
        Pais::create(['descricao' => 'Palau', 'codigo_bacen' => 5754]);
        Pais::create(['descricao' => 'Paquistão', 'codigo_bacen' => 5762]);
        Pais::create(['descricao' => 'Panamá', 'codigo_bacen' => 5800]);
        Pais::create(['descricao' => 'Paraguai', 'codigo_bacen' => 5860]);
        Pais::create(['descricao' => 'Peru', 'codigo_bacen' => 5894]);
        Pais::create(['descricao' => 'Pitcairn, Ilha', 'codigo_bacen' => 5932]);
        Pais::create(['descricao' => 'Polinésia Francesa', 'codigo_bacen' => 5991]);
        Pais::create(['descricao' => 'Polônia, República da', 'codigo_bacen' => 6033]);
        Pais::create(['descricao' => 'Portugal', 'codigo_bacen' => 6076]);
        Pais::create(['descricao' => 'Porto Rico', 'codigo_bacen' => 6114]);
        Pais::create(['descricao' => 'Quênia', 'codigo_bacen' => 6238]);
        Pais::create(['descricao' => 'Quirguiz, República', 'codigo_bacen' => 6254]);
        Pais::create(['descricao' => 'Escócia', 'codigo_bacen' => 6289]);
        Pais::create(['descricao' => 'Gales, País de', 'codigo_bacen' => 6289]);
        Pais::create(['descricao' => 'Grã-Bretanha', 'codigo_bacen' => 6289]);
        Pais::create(['descricao' => 'Inglaterra', 'codigo_bacen' => 6289]);
        Pais::create(['descricao' => 'Irlanda do Norte', 'codigo_bacen' => 6289]);
        Pais::create(['descricao' => 'Reino Unido', 'codigo_bacen' => 6289]);
        Pais::create(['descricao' => 'República Centro-Africana', 'codigo_bacen' => 6408]);
        Pais::create(['descricao' => 'República Dominicana', 'codigo_bacen' => 6475]);
        Pais::create(['descricao' => 'Reunião, Ilha', 'codigo_bacen' => 6602]);
        Pais::create(['descricao' => 'Zimbábue', 'codigo_bacen' => 6653]);
        Pais::create(['descricao' => 'Romênia', 'codigo_bacen' => 6700]);
        Pais::create(['descricao' => 'Ruanda', 'codigo_bacen' => 6750]);
        Pais::create(['descricao' => 'Rússia', 'codigo_bacen' => 6769]);
        Pais::create(['descricao' => 'Salomão, Ilhas', 'codigo_bacen' => 6777]);
        Pais::create(['descricao' => 'Saara Ocidental', 'codigo_bacen' => 6858]);
        Pais::create(['descricao' => 'El Salvador', 'codigo_bacen' => 6874]);
        Pais::create(['descricao' => 'Samoa', 'codigo_bacen' => 6904]);
        Pais::create(['descricao' => 'Samoa Americana', 'codigo_bacen' => 6912]);
        Pais::create(['descricao' => 'São Cristóvão e Neves', 'codigo_bacen' => 6955]);
        Pais::create(['descricao' => 'San Marino', 'codigo_bacen' => 6971]);
        Pais::create(['descricao' => 'São Pedro e Miquelon', 'codigo_bacen' => 7005]);
        Pais::create(['descricao' => 'São Vicente e Granadinas', 'codigo_bacen' => 7056]);
        Pais::create(['descricao' => 'Santa Helena', 'codigo_bacen' => 7102]);
        Pais::create(['descricao' => 'Santa Lúcia', 'codigo_bacen' => 7153]);
        Pais::create(['descricao' => 'São Tomé e Príncipe, Ilhas', 'codigo_bacen' => 7200]);
        Pais::create(['descricao' => 'Senegal', 'codigo_bacen' => 7285]);
        Pais::create(['descricao' => 'Seychelles', 'codigo_bacen' => 7315]);
        Pais::create(['descricao' => 'Serra Leoa', 'codigo_bacen' => 7358]);
        Pais::create(['descricao' => 'Cingapura', 'codigo_bacen' => 7412]);
        Pais::create(['descricao' => 'Síria, República Árabe da', 'codigo_bacen' => 7447]);
        Pais::create(['descricao' => 'Somália', 'codigo_bacen' => 7480]);
        Pais::create(['descricao' => 'Sri Lanka', 'codigo_bacen' => 7501]);
        Pais::create(['descricao' => 'Suazilândia', 'codigo_bacen' => 7544]);
        Pais::create(['descricao' => 'África do Sul', 'codigo_bacen' => 7560]);
        Pais::create(['descricao' => 'Sudão', 'codigo_bacen' => 7595]);
        Pais::create(['descricao' => 'Suécia', 'codigo_bacen' => 7641]);
        Pais::create(['descricao' => 'Suíça', 'codigo_bacen' => 7676]);
        Pais::create(['descricao' => 'Suriname', 'codigo_bacen' => 7706]);
        Pais::create(['descricao' => 'Tadjiquistão', 'codigo_bacen' => 7722]);
        Pais::create(['descricao' => 'Tailândia', 'codigo_bacen' => 7765]);
        Pais::create(['descricao' => 'Tanzânia, República Unida da', 'codigo_bacen' => 7803]);
        Pais::create(['descricao' => 'Território Britânico Oc. Índico', 'codigo_bacen' => 7820]);
        Pais::create(['descricao' => 'Djibuti', 'codigo_bacen' => 7838]);
        Pais::create(['descricao' => 'Chade', 'codigo_bacen' => 7889]);
        Pais::create(['descricao' => 'Tcheca, República', 'codigo_bacen' => 7919]);
        Pais::create(['descricao' => 'Timor Leste', 'codigo_bacen' => 7951]);
        Pais::create(['descricao' => 'Togo', 'codigo_bacen' => 8001]);
        Pais::create(['descricao' => 'Toquelau, Ilhas', 'codigo_bacen' => 8052]);
        Pais::create(['descricao' => 'Tonga', 'codigo_bacen' => 8109]);
        Pais::create(['descricao' => 'Trinidad e Tobago', 'codigo_bacen' => 8150]);
        Pais::create(['descricao' => 'Tunísia', 'codigo_bacen' => 8206]);
        Pais::create(['descricao' => 'Turcas e Caicos, Ilhas', 'codigo_bacen' => 8230]);
        Pais::create(['descricao' => 'Turcomenistão, República do', 'codigo_bacen' => 8249]);
        Pais::create(['descricao' => 'Turquia', 'codigo_bacen' => 8273]);
        Pais::create(['descricao' => 'Tuvalu', 'codigo_bacen' => 8281]);
        Pais::create(['descricao' => 'Ucrânia', 'codigo_bacen' => 8311]);
        Pais::create(['descricao' => 'Uganda', 'codigo_bacen' => 8338]);
        Pais::create(['descricao' => 'Uruguai', 'codigo_bacen' => 8451]);
        Pais::create(['descricao' => 'Uzbequistão, República do', 'codigo_bacen' => 8478]);
        Pais::create(['descricao' => 'Vaticano, Estado da Cidade do', 'codigo_bacen' => 8486]);
        Pais::create(['descricao' => 'Venezuela', 'codigo_bacen' => 8508]);
        Pais::create(['descricao' => 'Vietnã', 'codigo_bacen' => 8583]);
        Pais::create(['descricao' => 'Virgens, Ilhas (Britânicas', 'codigo_bacen' => 8630]);
        Pais::create(['descricao' => 'Virgens, Ilhas (E.U.A.', 'codigo_bacen' => 8664]);
        Pais::create(['descricao' => 'Fiji', 'codigo_bacen' => 8702]);
        Pais::create(['descricao' => 'Wake, Ilha', 'codigo_bacen' => 8737]);
        Pais::create(['descricao' => 'Wallis e Futuna, Ilhas', 'codigo_bacen' => 8753]);
        Pais::create(['descricao' => 'Congo, República Democrática do', 'codigo_bacen' => 8885]);
        Pais::create(['descricao' => 'Zâmbia', 'codigo_bacen' => 8907]);
        Pais::create(['descricao' => 'Zona do Canal do Panamá', 'codigo_bacen' => 8958]);

    }
}
