<?php

use App\Projeto;
use Illuminate\Database\Seeder;

class ProjetoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $p1 = Projeto::create(['descricao' => 'CARDIGITAL-1', 'prioridade' => 1, 'equipe_id' => 1]);
        $p2 = Projeto::create(['descricao' => 'VIVARA-1', 'prioridade' => 2, 'equipe_id' => 4]);
        $p3 = Projeto::create(['descricao' => 'NEGNTMSG-1', 'prioridade' => 3, 'equipe_id' => 4]);
        $p4 = Projeto::create(['descricao' => 'CHAINTTS-1', 'prioridade' => 4, 'equipe_id' => 1]);
        $p5 = Projeto::create(['descricao' => 'ALTCUPOMAO-1', 'prioridade' => 5, 'equipe_id' => 1]);
        $p6 = Projeto::create(['descricao' => 'NUMSORTE-1', 'prioridade' => 6, 'equipe_id' => 1]);
        $p7 = Projeto::create(['descricao' => 'INTDEV-16', 'prioridade' => 7, 'equipe_id' => 1]);
        $p8 = Projeto::create(['descricao' => 'PESQSATISF-25', 'prioridade' => 8, 'equipe_id' => 1]);
        $p9 = Projeto::create(['descricao' => 'LISTAEXT-1', 'prioridade' => 9, 'equipe_id' => 1]);
        $p10 = Projeto::create(['descricao' => 'PRSGF-1', 'prioridade' => 10, 'equipe_id' => 1]);
        $p11 = Projeto::create(['descricao' => 'ANGDEVOL-1', 'prioridade' => 11, 'equipe_id' => 1]);
        $p12 = Projeto::create(['descricao' => 'DOTZAPI-1', 'prioridade' => 12, 'equipe_id' => 1]);
        $p13 = Projeto::create(['descricao' => 'CONTPEDIDO-1', 'prioridade' => 13, 'equipe_id' => 1]);
        $p14 = Projeto::create(['descricao' => 'PRBVV-98', 'prioridade' => 14, 'equipe_id' => 1]);
        $p15 = Projeto::create(['descricao' => 'ZANFISANGO-1', 'prioridade' => 15, 'equipe_id' => 1]);
        $p16 = Projeto::create(['descricao' => 'NOTA2019-1', 'prioridade' => 16, 'equipe_id' => 1]);
        $p17 = Projeto::create(['descricao' => 'SELFDINAM-1', 'prioridade' => 17, 'equipe_id' => 1]);
        $p18 = Projeto::create(['descricao' => 'BL-6600', 'prioridade' => 18, 'equipe_id' => 1]);
        $p19 = Projeto::create(['descricao' => 'TROCASEMCP-1', 'prioridade' => 19, 'equipe_id' => 1]);
        $p20 = Projeto::create(['descricao' => 'INFOCHEQUE-1', 'prioridade' => 20, 'equipe_id' => 1]);
        $p21 = Projeto::create(['descricao' => 'PESQSATISF-42', 'prioridade' => 21, 'equipe_id' => 1]);
        $p22 = Projeto::create(['descricao' => 'TROCOSIMPL-1', 'prioridade' => 22, 'equipe_id' => 1]);
        $p23 = Projeto::create(['descricao' => 'NEWETIQ-1', 'prioridade' => 23, 'equipe_id' => 1]);
        $p24 = Projeto::create(['descricao' => 'SUPERTROCO-1', 'prioridade' => 24, 'equipe_id' => 1]);
        $p25 = Projeto::create(['descricao' => 'INTTAXWEB-1', 'prioridade' => 25, 'equipe_id' => 2]);
        $p26 = Projeto::create(['descricao' => 'PR-60', 'prioridade' => 26, 'equipe_id' => 1]);
        $p27 = Projeto::create(['descricao' => 'ZANPOSTO-1', 'prioridade' => 27, 'equipe_id' => 1]);
        $p28 = Projeto::create(['descricao' => 'VIAINTCRES-1', 'prioridade' => 28, 'equipe_id' => 1]);
        $p29 = Projeto::create(['descricao' => 'BL-6718 / 6719', 'prioridade' => 29, 'equipe_id' => 1]);
        $p30 = Projeto::create(['descricao' => 'MOVTESLOJA-1', 'prioridade' => 30, 'equipe_id' => 1]);
        $p31 = Projeto::create(['descricao' => 'CARDIGITI-1', 'prioridade' => 31, 'equipe_id' => 1]);
        $p32 = Projeto::create(['descricao' => 'IBOPEDTM-1', 'prioridade' => 32, 'equipe_id' => 1]);
        $p33 = Projeto::create(['descricao' => 'CORRECPGT-1', 'prioridade' => 33, 'equipe_id' => 1]);
        $p34 = Projeto::create(['descricao' => 'NEGCANCDE-1', 'prioridade' => 34, 'equipe_id' => 4]);
        $p35 = Projeto::create(['descricao' => 'NEGENDMERC-1 ', 'prioridade' => 35, 'equipe_id' => 4]);
        $p36 = Projeto::create(['descricao' => 'PROMOAPP-1', 'prioridade' => 36, 'equipe_id' => 1]);
        $p37 = Projeto::create(['descricao' => 'INTBOLETO-1', 'prioridade' => 37, 'equipe_id' => 2]);
        $p38 = Projeto::create(['descricao' => 'MAKMASTSAF-1', 'prioridade' => 38, 'equipe_id' => 2]);
        $p39 = Projeto::create(['descricao' => 'VNDAPRAZO-1', 'prioridade' => 39, 'equipe_id' => 2]);
        $p40 = Projeto::create(['descricao' => 'MAKM40F1-1', 'prioridade' => 40, 'equipe_id' => 2]);
        $p41 = Projeto::create(['descricao' => 'INTM40CAD-1', 'prioridade' => 41, 'equipe_id' => 2]);
        $p42 = Projeto::create(['descricao' => 'MAKREL-1', 'prioridade' => 42, 'equipe_id' => 2]);
        $p43 = Projeto::create(['descricao' => 'MAKDEV-1', 'prioridade' => 43, 'equipe_id' => 2]);
        $p44 = Projeto::create(['descricao' => 'RESATOTCAR-1', 'prioridade' => 44, 'equipe_id' => 2]);
        $p45 = Projeto::create(['descricao' => 'VCMEMORIA-1', 'prioridade' => 45, 'equipe_id' => 2]);
        $p46 = Projeto::create(['descricao' => 'GERABOLETO-1', 'prioridade' => 46, 'equipe_id' => 2]);
        $p47 = Projeto::create(['descricao' => 'RELVALECOM-1', 'prioridade' => 47, 'equipe_id' => 2]);
        $p48 = Projeto::create(['descricao' => 'ZANBILLSAS-1', 'prioridade' => 48, 'equipe_id' => 3]);
        $p49 = Projeto::create(['descricao' => 'PRFAMDPTO-1', 'prioridade' => 49, 'equipe_id' => 1]);
        $p50 = Projeto::create(['descricao' => 'ETIQPREMB-1', 'prioridade' => 50, 'equipe_id' => 4]);
        $p51 = Projeto::create(['descricao' => 'VIVARAPDV-1', 'prioridade' => 51, 'equipe_id' => 4]);
        $p52 = Projeto::create(['descricao' => 'MODIFANGOL-1', 'prioridade' => 52, 'equipe_id' => 1]);
        $p53 = Projeto::create(['descricao' => 'DESCPMZ-1', 'prioridade' => 53, 'equipe_id' => 1]);
        $p54 = Projeto::create(['descricao' => 'DECRFIDVEN-1', 'prioridade' => 54, 'equipe_id' => 1]);
        $p55 = Projeto::create(['descricao' => 'CANCRFID-1', 'prioridade' => 55, 'equipe_id' => 1]);
        $p56 = Projeto::create(['descricao' => 'CASALOJIST-1', 'prioridade' => 56, 'equipe_id' => 4]);
        $p57 = Projeto::create(['descricao' => 'INTEZTECH-1', 'prioridade' => 57, 'equipe_id' => 1]);
        $p58 = Projeto::create(['descricao' => 'MLCOMANDA-1', 'prioridade' => 58, 'equipe_id' => 1]);
        $p59 = Projeto::create(['descricao' => 'MELHORIAVP-1', 'prioridade' => 59, 'equipe_id' => 1]);
        $p60 = Projeto::create(['descricao' => 'SCANNERJAD-1', 'prioridade' => 60, 'equipe_id' => 1]);
        $p61 = Projeto::create(['descricao' => 'TORVCCORTE-1', 'prioridade' => 61, 'equipe_id' => 1]);
        $p62 = Projeto::create(['descricao' => 'ZANINTALOC-1', 'prioridade' => 62, 'equipe_id' => 1]);
        $p63 = Projeto::create(['descricao' => 'INTPINPAD-1', 'prioridade' => 63, 'equipe_id' => 1]);
        $p64 = Projeto::create(['descricao' => 'MAKESTACI-1', 'prioridade' => 64, 'equipe_id' => 1]);
        $p65 = Projeto::create(['descricao' => 'NESPRESSO-1', 'prioridade' => 65, 'equipe_id' => 4]);
        $p66 = Projeto::create(['descricao' => 'PR-21', 'prioridade' => 66, 'equipe_id' => 1]);
        $p67 = Projeto::create(['descricao' => 'INTRETAIL-1', 'prioridade' => 67, 'equipe_id' => 2]);
        $p68 = Projeto::create(['descricao' => 'SAASAUTO-1', 'prioridade' => 68, 'equipe_id' => 3]);
        $p69 = Projeto::create(['descricao' => 'COMZ-1', 'prioridade' => 69, 'equipe_id' => 3]);
        $p70 = Projeto::create(['descricao' => 'INTVORTICE-1', 'prioridade' => 70, 'equipe_id' => 1]);
        $p71 = Projeto::create(['descricao' => 'NPSFASE5-1', 'prioridade' => 71, 'equipe_id' => 1]);
        $p72 = Projeto::create(['descricao' => 'SPACECARD-1', 'prioridade' => 72, 'equipe_id' => 1]);
        $p73 = Projeto::create(['descricao' => 'VENDAEMB-1', 'prioridade' => 73, 'equipe_id' => 4]);
        $p74 = Projeto::create(['descricao' => 'ATUALIZPDV-1', 'prioridade' => 74, 'equipe_id' => 1]);
        $p75 = Projeto::create(['descricao' => 'PROMOQTDE-1', 'prioridade' => 75, 'equipe_id' => 1]);
        $p76 = Projeto::create(['descricao' => 'NESPRESSOCOMPLEMENTO-1', 'prioridade' => 76, 'equipe_id' => 4]);
        $p77 = Projeto::create(['descricao' => 'PROSEGURCM-1', 'prioridade' => 77, 'equipe_id' => 1]);
        $p78 = Projeto::create(['descricao' => 'TOKENWPS-1', 'prioridade' => 78, 'equipe_id' => 1]);
        $p79 = Projeto::create(['descricao' => 'VAANDROID-1', 'prioridade' => 79, 'equipe_id' => 5]);
        $p80 = Projeto::create(['descricao' => 'ML-1288', 'prioridade' => 80, 'equipe_id' => 1]);
        $p81 = Projeto::create(['descricao' => 'PAYFACE-1', 'prioridade' => 81, 'equipe_id' => 1]);
        $p82 = Projeto::create(['descricao' => 'PROMOCONV-1', 'prioridade' => 82, 'equipe_id' => 1]);
        $p83 = Projeto::create(['descricao' => 'CONSULPROD-1', 'prioridade' => 83, 'equipe_id' => 4]);
        $p84 = Projeto::create(['descricao' => 'PROPZ-1', 'prioridade' => 84, 'equipe_id' => 1]);
        $p85 = Projeto::create(['descricao' => 'DESIMPTEF-1', 'prioridade' => 85, 'equipe_id' => 1]);
        $p86 = Projeto::create(['descricao' => 'UPLIFT-1', 'prioridade' => 86, 'equipe_id' => 1]);
        $p87 = Projeto::create(['descricao' => 'PROMOAPP2-1', 'prioridade' => 87, 'equipe_id' => 1]);
        $p88 = Projeto::create(['descricao' => 'INTPDVSAP-1', 'prioridade' => 88, 'equipe_id' => 1]);
        $p89 = Projeto::create(['descricao' => 'PETINTKALU-1', 'prioridade' => 89, 'equipe_id' => 1]);
        $p90 = Projeto::create(['descricao' => 'PARKPLUS-2', 'prioridade' => 90, 'equipe_id' => 1]);
        $p91 = Projeto::create(['descricao' => 'SENHADIA-1', 'prioridade' => 91, 'equipe_id' => 2]);
        $p92 = Projeto::create(['descricao' => 'TROCACPLJ-1', 'prioridade' => 92, 'equipe_id' => 1]);
        $p93 = Projeto::create(['descricao' => 'SAIDAOPER-1', 'prioridade' => 93, 'equipe_id' => 1]);
        $p94 = Projeto::create(['descricao' => 'MELHORIASAPP-1', 'prioridade' => 94, 'equipe_id' => 5]);
        $p95 = Projeto::create(['descricao' => 'PAYFACEAPP-1', 'prioridade' => 95, 'equipe_id' => 5]);
        $p96 = Projeto::create(['descricao' => 'MZCANCANT-1', 'prioridade' => 96, 'equipe_id' => 1]);
        $p97 = Projeto::create(['descricao' => 'ACRESCITEM-1', 'prioridade' => 97, 'equipe_id' => 1]);
        $p98 = Projeto::create(['descricao' => 'TROCASEMCV-1', 'prioridade' => 98, 'equipe_id' => 1]);
        $p99 = Projeto::create(['descricao' => 'PGSOROCRED-1', 'prioridade' => 99, 'equipe_id' => 1]);
        $p100 = Projeto::create(['descricao' => 'COBNEPOS-1', 'prioridade' => 100, 'equipe_id' => 1]);
        $p101 = Projeto::create(['descricao' => 'PETENTREGA-1', 'prioridade' => 101, 'equipe_id' => 1]);
        $p102 = Projeto::create(['descricao' => 'CRMONEID-1', 'prioridade' => 102, 'equipe_id' => 1]);
        $p103 = Projeto::create(['descricao' => 'TENDENCIA-1', 'prioridade' => 103, 'equipe_id' => 1]);
        $p104 = Projeto::create(['descricao' => 'FACTURAA4-1', 'prioridade' => 104, 'equipe_id' => 1]);
        $p105 = Projeto::create(['descricao' => 'VALIDAEP-1', 'prioridade' => 105, 'equipe_id' => 1]);
        $p106 = Projeto::create(['descricao' => 'SORTEIOFIN-1', 'prioridade' => 106, 'equipe_id' => 1]);
        $p107 = Projeto::create(['descricao' => 'CADSORTEIO-1', 'prioridade' => 107, 'equipe_id' => 1]);
        $p108 = Projeto::create(['descricao' => 'AUDITTROCA-1', 'prioridade' => 108, 'equipe_id' => 1]);
        $p109 = Projeto::create(['descricao' => 'PERTO-1', 'prioridade' => 109, 'equipe_id' => 1]);
        $p110 = Projeto::create(['descricao' => 'INTMELIUZ-1', 'prioridade' => 110, 'equipe_id' => 1]);
        $p111 = Projeto::create(['descricao' => 'WEDOO-1', 'prioridade' => 111, 'equipe_id' => 1]);
        $p112 = Projeto::create(['descricao' => 'NPSFASE6-1', 'prioridade' => 112, 'equipe_id' => 1]);
        $p113 = Projeto::create(['descricao' => 'VPTELAPDV-1', 'prioridade' => 113, 'equipe_id' => 1]);
        $p114 = Projeto::create(['descricao' => 'PROMOLISTA-1', 'prioridade' => 114, 'equipe_id' => 1]);
        $p115 = Projeto::create(['descricao' => 'LOGVOUCHER-1', 'prioridade' => 115, 'equipe_id' => 1]);
        $p116 = Projeto::create(['descricao' => 'APPDMCARD-1', 'prioridade' => 116, 'equipe_id' => 1]);
        $p117 = Projeto::create(['descricao' => 'STOPBANK-1', 'prioridade' => 117, 'equipe_id' => 1]);
        $p118 = Projeto::create(['descricao' => 'CUSTSPICY-1', 'prioridade' => 118, 'equipe_id' => 1]);
        $p119 = Projeto::create(['descricao' => 'INTJOYA-1', 'prioridade' => 119, 'equipe_id' => 1]);
        $p120 = Projeto::create(['descricao' => 'ORDEMSERV-1', 'prioridade' => 120, 'equipe_id' => 1]);
        $p121 = Projeto::create(['descricao' => 'AJUSTNFCE-1', 'prioridade' => 121, 'equipe_id' => 1]);
        $p122 = Projeto::create(['descricao' => 'ARREDONDAR-1', 'prioridade' => 122, 'equipe_id' => 1]);
        $p123 = Projeto::create(['descricao' => 'CTRBLOCOX-1', 'prioridade' => 123, 'equipe_id' => 1]);
        $p124 = Projeto::create(['descricao' => 'CRMSAC-1', 'prioridade' => 124, 'equipe_id' => 1]);
        $p125 = Projeto::create(['descricao' => 'CRMPONTOS-1', 'prioridade' => 125, 'equipe_id' => 1]);
        $p126 = Projeto::create(['descricao' => 'INTBOOME-1', 'prioridade' => 126, 'equipe_id' => 1]);
        $p127 = Projeto::create(['descricao' => 'PROTHEUS2-1', 'prioridade' => 127, 'equipe_id' => 1]);
        $p128 = Projeto::create(['descricao' => 'PETENTREGA2-1', 'prioridade' => 128, 'equipe_id' => 1]);
        $p129 = Projeto::create(['descricao' => 'INTADYENF1-1', 'prioridade' => 129, 'equipe_id' => 1]);
        $p130 = Projeto::create(['descricao' => 'CANCDEV-39', 'prioridade' => 130, 'equipe_id' => 2]);
        $p131 = Projeto::create(['descricao' => 'LOPNOVGISS-1', 'prioridade' => 131, 'equipe_id' => 1]);
        $p132 = Projeto::create(['descricao' => 'SINALSELF-1', 'prioridade' => 132, 'equipe_id' => 1]);
        $p133 = Projeto::create(['descricao' => 'DEVITEMPR-1', 'prioridade' => 133, 'equipe_id' => 1]);
        $p134 = Projeto::create(['descricao' => 'INTTODOCAR-1', 'prioridade' => 134, 'equipe_id' => 1]);
        $p135 = Projeto::create(['descricao' => 'LISTADESC-1', 'prioridade' => 135, 'equipe_id' => 1]);
        $p136 = Projeto::create(['descricao' => 'POMPEIA-1', 'prioridade' => 136, 'equipe_id' => 1]);
        $p137 = Projeto::create(['descricao' => 'PRODCOMB-1', 'prioridade' => 137, 'equipe_id' => 1]);
        $p138 = Projeto::create(['descricao' => 'POPUPMERC-1', 'prioridade' => 138, 'equipe_id' => 1]);
        $p139 = Projeto::create(['descricao' => 'DOTZLGPD-1', 'prioridade' => 139, 'equipe_id' => 1]);
        $p140 = Projeto::create(['descricao' => 'INTCATRACA-1', 'prioridade' => 140, 'equipe_id' => 1]);
        $p141 = Projeto::create(['descricao' => 'NFECOMPLE-1', 'prioridade' => 141, 'equipe_id' => 1]);
        $p142 = Projeto::create(['descricao' => 'CONFTURNO-1', 'prioridade' => 142, 'equipe_id' => 1]);
        $p143 = Projeto::create(['descricao' => 'MERCAFACIL-1A', 'prioridade' => 143, 'equipe_id' => 1]);
        $p144 = Projeto::create(['descricao' => 'MERCAFACIL-1B', 'prioridade' => 144, 'equipe_id' => 1]);
        $p145 = Projeto::create(['descricao' => 'TOTAUTOSER-1', 'prioridade' => 145, 'equipe_id' => 1]);
        $p146 = Projeto::create(['descricao' => 'PRDESCRAT-1', 'prioridade' => 146, 'equipe_id' => 1]);
        $p147 = Projeto::create(['descricao' => 'TOTCONDUCT-1', 'prioridade' => 147, 'equipe_id' => 1]);
        $p148 = Projeto::create(['descricao' => 'NFCEMODULO-1', 'prioridade' => 148, 'equipe_id' => 1]);
        $p149 = Projeto::create(['descricao' => 'INTAPIPR-1', 'prioridade' => 149, 'equipe_id' => 1]);
        $p150 = Projeto::create(['descricao' => 'CONTPESO-1', 'prioridade' => 150, 'equipe_id' => 1]);
        $p151 = Projeto::create(['descricao' => 'DEVSEMCP-1', 'prioridade' => 151, 'equipe_id' => 1]);
        $p152 = Projeto::create(['descricao' => 'QRCODEGPOS-1', 'prioridade' => 152, 'equipe_id' => 1]);
        $p153 = Projeto::create(['descricao' => 'ZANVOUKERN-1', 'prioridade' => 153, 'equipe_id' => 1]);
        $p154 = Projeto::create(['descricao' => 'ALTENTNF-1', 'prioridade' => 154, 'equipe_id' => 1]);
        $p155 = Projeto::create(['descricao' => 'NEWBLOCOX-1', 'prioridade' => 155, 'equipe_id' => 1]);
        $p156 = Projeto::create(['descricao' => 'ZANSATAJUS-1', 'prioridade' => 156, 'equipe_id' => 1]);
        $p157 = Projeto::create(['descricao' => 'PCF2-1', 'prioridade' => 157, 'equipe_id' => 1]);
        $p158 = Projeto::create(['descricao' => 'ZANINTDFIS-1', 'prioridade' => 158, 'equipe_id' => 1]);
        $p159 = Projeto::create(['descricao' => 'ZANPROMFAC-1', 'prioridade' => 159, 'equipe_id' => 1]);
        $p160 = Projeto::create(['descricao' => 'CANCDEV-1', 'prioridade' => 160, 'equipe_id' => 1]);
        $p161 = Projeto::create(['descricao' => 'BLOQCAMPO-1', 'prioridade' => 161, 'equipe_id' => 1]);
        $p162 = Projeto::create(['descricao' => 'CLOBLOJA-1', 'prioridade' => 162, 'equipe_id' => 1]);
        $p163 = Projeto::create(['descricao' => 'CANCDEV-1', 'prioridade' => 163, 'equipe_id' => 1]);
    }
}
