<?php

use App\Projeto;
use Illuminate\Database\Seeder;

class ProjetoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $p2 = Projeto::create(['descricao' => 'VIVARA-1', 'equipe_id' => 4, 'status' => 3, 'status_aprovacao' => 2]);
        $p3 = Projeto::create(['descricao' => 'NEGNTMSG-1', 'equipe_id' => 4, 'status' => 3, 'status_aprovacao' => 2]);
        $p4 = Projeto::create(['descricao' => 'CHAINTTS-1', 'equipe_id' => 1, 'status' => 3, 'status_aprovacao' => 2]);
        $p5 = Projeto::create(['descricao' => 'ALTCUPOMAO-1', 'equipe_id' => 1, 'status' => 3, 'status_aprovacao' => 2]);
        $p6 = Projeto::create(['descricao' => 'NUMSORTE-1', 'equipe_id' => 1, 'status' => 3, 'status_aprovacao' => 2]);
        $p7 = Projeto::create(['descricao' => 'INTDEV-16', 'equipe_id' => 1, 'status' => 3, 'status_aprovacao' => 2]);
        $p8 = Projeto::create(['descricao' => 'PESQSATISF-25', 'equipe_id' => 1, 'status' => 3, 'status_aprovacao' => 2]);
        $p9 = Projeto::create(['descricao' => 'LISTAEXT-1', 'equipe_id' => 1, 'status' => 3, 'status_aprovacao' => 2]);
        $p10 = Projeto::create(['descricao' => 'PRSGF-1', 'equipe_id' => 1, 'status' => 3, 'status_aprovacao' => 2]);
        $p11 = Projeto::create(['descricao' => 'ANGDEVOL-1', 'equipe_id' => 1, 'status' => 3, 'status_aprovacao' => 2]);
        $p12 = Projeto::create(['descricao' => 'DOTZAPI-1', 'equipe_id' => 1, 'status' => 3, 'status_aprovacao' => 2]);
        $p13 = Projeto::create(['descricao' => 'CONTPEDIDO-1', 'equipe_id' => 1, 'status' => 3, 'status_aprovacao' => 2]);
        $p14 = Projeto::create(['descricao' => 'PRBVV-98', 'equipe_id' => 1, 'status' => 3, 'status_aprovacao' => 2]);
        $p15 = Projeto::create(['descricao' => 'ZANFISANGO-1', 'equipe_id' => 1, 'status' => 3, 'status_aprovacao' => 2]);
        $p16 = Projeto::create(['descricao' => 'NOTA2019-1', 'equipe_id' => 1, 'status' => 3, 'status_aprovacao' => 2]);
        $p17 = Projeto::create(['descricao' => 'SELFDINAM-1', 'equipe_id' => 1, 'status' => 3, 'status_aprovacao' => 2]);
        $p18 = Projeto::create(['descricao' => 'BL-6600', 'equipe_id' => 1, 'status' => 3, 'status_aprovacao' => 2]);
        $p19 = Projeto::create(['descricao' => 'TROCASEMCP-1', 'equipe_id' => 1, 'status' => 3, 'status_aprovacao' => 2]);
        $p20 = Projeto::create(['descricao' => 'INFOCHEQUE-1', 'equipe_id' => 1, 'status' => 3, 'status_aprovacao' => 2]);
        $p21 = Projeto::create(['descricao' => 'PESQSATISF-42', 'equipe_id' => 1, 'status' => 3, 'status_aprovacao' => 2]);
        $p22 = Projeto::create(['descricao' => 'TROCOSIMPL-1', 'equipe_id' => 1, 'status' => 3, 'status_aprovacao' => 2]);
        $p23 = Projeto::create(['descricao' => 'NEWETIQ-1', 'equipe_id' => 1, 'status' => 3, 'status_aprovacao' => 2]);
        $p24 = Projeto::create(['descricao' => 'SUPERTROCO-1', 'equipe_id' => 1, 'status' => 3, 'status_aprovacao' => 2]);
        $p25 = Projeto::create(['descricao' => 'INTTAXWEB-1', 'equipe_id' => 2, 'status' => 3, 'status_aprovacao' => 2]);
        $p26 = Projeto::create(['descricao' => 'PR-60', 'equipe_id' => 1, 'status' => 3, 'status_aprovacao' => 2]);
        $p27 = Projeto::create(['descricao' => 'ZANPOSTO-1', 'equipe_id' => 1, 'status' => 3, 'status_aprovacao' => 2]);
        $p28 = Projeto::create(['descricao' => 'VIAINTCRES-1', 'equipe_id' => 1, 'status' => 3, 'status_aprovacao' => 2]);
        $p29 = Projeto::create(['descricao' => 'BL-6718 / 6719', 'equipe_id' => 1, 'status' => 3, 'status_aprovacao' => 2]);
        $p30 = Projeto::create(['descricao' => 'MOVTESLOJA-1', 'equipe_id' => 1, 'status' => 3, 'status_aprovacao' => 2]);
        $p31 = Projeto::create(['descricao' => 'CARDIGITI-1', 'equipe_id' => 1, 'status' => 3, 'status_aprovacao' => 2]);
        $p32 = Projeto::create(['descricao' => 'IBOPEDTM-1', 'equipe_id' => 1, 'status' => 3, 'status_aprovacao' => 2]);
        $p33 = Projeto::create(['descricao' => 'CORRECPGT-1', 'equipe_id' => 1, 'status' => 3, 'status_aprovacao' => 2]);
        $p34 = Projeto::create(['descricao' => 'NEGCANCDE-1', 'equipe_id' => 4, 'status' => 3, 'status_aprovacao' => 2]);
        $p35 = Projeto::create(['descricao' => 'NEGENDMERC-1 ', 'equipe_id' => 4, 'status' => 3, 'status_aprovacao' => 2]);
        $p36 = Projeto::create(['descricao' => 'PROMOAPP-1', 'equipe_id' => 1, 'status' => 3, 'status_aprovacao' => 2]);
        $p37 = Projeto::create(['descricao' => 'INTBOLETO-1', 'equipe_id' => 2, 'status' => 3, 'status_aprovacao' => 2]);
        $p38 = Projeto::create(['descricao' => 'MAKMASTSAF-1', 'equipe_id' => 2, 'status' => 3, 'status_aprovacao' => 2]);
        $p39 = Projeto::create(['descricao' => 'VNDAPRAZO-1', 'equipe_id' => 2, 'status' => 3, 'status_aprovacao' => 2]);
        $p40 = Projeto::create(['descricao' => 'MAKM40F1-1', 'equipe_id' => 2, 'status' => 3, 'status_aprovacao' => 2]);
        $p41 = Projeto::create(['descricao' => 'INTM40CAD-1', 'equipe_id' => 2, 'status' => 3, 'status_aprovacao' => 2]);
        $p42 = Projeto::create(['descricao' => 'MAKREL-1', 'equipe_id' => 2, 'status' => 3, 'status_aprovacao' => 2]);
        $p43 = Projeto::create(['descricao' => 'MAKDEV-1', 'equipe_id' => 2, 'status' => 3, 'status_aprovacao' => 2]);
        $p44 = Projeto::create(['descricao' => 'RESATOTCAR-1', 'equipe_id' => 2, 'status' => 3, 'status_aprovacao' => 2]);
        $p45 = Projeto::create(['descricao' => 'VCMEMORIA-1', 'equipe_id' => 2, 'status' => 3, 'status_aprovacao' => 2]);
        $p46 = Projeto::create(['descricao' => 'GERABOLETO-1', 'equipe_id' => 2, 'status' => 3, 'status_aprovacao' => 2]);
        $p47 = Projeto::create(['descricao' => 'RELVALECOM-1', 'equipe_id' => 2, 'status' => 3, 'status_aprovacao' => 2]);
        $p48 = Projeto::create(['descricao' => 'ZANBILLSAS-1', 'equipe_id' => 3, 'status' => 3, 'status_aprovacao' => 2]);
        $p49 = Projeto::create(['descricao' => 'PRFAMDPTO-1', 'equipe_id' => 1, 'status' => 3, 'status_aprovacao' => 2]);
        $p50 = Projeto::create(['descricao' => 'ETIQPREMB-1', 'equipe_id' => 4, 'status' => 3, 'status_aprovacao' => 2]);
        $p51 = Projeto::create(['descricao' => 'VIVARAPDV-1', 'equipe_id' => 4, 'status' => 3, 'status_aprovacao' => 2]);
        $p52 = Projeto::create(['descricao' => 'MODIFANGOL-1', 'equipe_id' => 1, 'status' => 3, 'status_aprovacao' => 2]);
        $p53 = Projeto::create(['descricao' => 'DESCPMZ-1', 'equipe_id' => 1, 'status' => 3, 'status_aprovacao' => 2]);
        $p54 = Projeto::create(['descricao' => 'DECRFIDVEN-1', 'equipe_id' => 1, 'status' => 1, 'status_aprovacao' => 2]);
        $p55 = Projeto::create(['descricao' => 'CANCRFID-1', 'equipe_id' => 1, 'status' => 1, 'status_aprovacao' => 2]);
        $p56 = Projeto::create(['descricao' => 'CASALOJIST-1', 'equipe_id' => 4, 'status' => 2, 'status_aprovacao' => 2]);
        $p57 = Projeto::create(['descricao' => 'INTEZTECH-1', 'equipe_id' => 1, 'status' => 1, 'status_aprovacao' => 2]);
        $p58 = Projeto::create(['descricao' => 'MLCOMANDA-1', 'equipe_id' => 1, 'status' => 1, 'status_aprovacao' => 2]);
        $p59 = Projeto::create(['descricao' => 'MELHORIAVP-1', 'equipe_id' => 1, 'status' => 1, 'status_aprovacao' => 2]);
        $p60 = Projeto::create(['descricao' => 'SCANNERJAD-1', 'equipe_id' => 1, 'status' => 2, 'status_aprovacao' => 2]);
        $p61 = Projeto::create(['descricao' => 'TORVCCORTE-1', 'equipe_id' => 1, 'status' => 1, 'status_aprovacao' => 2]);
        $p62 = Projeto::create(['descricao' => 'ZANINTALOC-1', 'equipe_id' => 1, 'status' => 2, 'status_aprovacao' => 2]);
        $p63 = Projeto::create(['descricao' => 'INTPINPAD-1', 'equipe_id' => 1, 'status' => 1, 'status_aprovacao' => 2]);
        $p64 = Projeto::create(['descricao' => 'MAKESTACI-1', 'equipe_id' => 1, 'status' => 2, 'status_aprovacao' => 2]);
        $p65 = Projeto::create(['descricao' => 'NESPRESSO-1', 'equipe_id' => 4, 'status' => 2, 'status_aprovacao' => 2]);
        $p66 = Projeto::create(['descricao' => 'PR-21', 'equipe_id' => 1, 'status' => 1, 'status_aprovacao' => 2]);
        $p67 = Projeto::create(['descricao' => 'INTRETAIL-1', 'equipe_id' => 2, 'status' => 2, 'status_aprovacao' => 2]);
        $p68 = Projeto::create(['descricao' => 'SAASAUTO-1', 'equipe_id' => 3, 'status' => 0, 'status_aprovacao' => 2]);
        $p69 = Projeto::create(['descricao' => 'COMZ-1', 'equipe_id' => 3, 'status' => 2, 'status_aprovacao' => 2]);
        $p70 = Projeto::create(['descricao' => 'INTVORTICE-1', 'equipe_id' => 1, 'status' => 1, 'status_aprovacao' => 2]);
        $p71 = Projeto::create(['descricao' => 'NPSFASE5-1', 'equipe_id' => 1, 'status' => 1, 'status_aprovacao' => 2]);
        $p72 = Projeto::create(['descricao' => 'SPACECARD-1', 'equipe_id' => 1, 'status' => 2, 'status_aprovacao' => 2]);
        $p73 = Projeto::create(['descricao' => 'VENDAEMB-1', 'equipe_id' => 4, 'status' => 1, 'status_aprovacao' => 2]);
        $p74 = Projeto::create(['descricao' => 'ATUALIZPDV-1', 'equipe_id' => 1, 'status' => 1, 'status_aprovacao' => 2]);
        $p75 = Projeto::create(['descricao' => 'PROMOQTDE-1', 'equipe_id' => 1, 'status' => 1, 'status_aprovacao' => 2]);
        $p76 = Projeto::create(['descricao' => 'NESPRESSOCOMPLEMENTO-1', 'equipe_id' => 4, 'status' => 0, 'status_aprovacao' => 2]);
        $p77 = Projeto::create(['descricao' => 'PROSEGURCM-1', 'equipe_id' => 1, 'status' => 1, 'status_aprovacao' => 2]);
        $p78 = Projeto::create(['descricao' => 'TOKENWPS-1', 'equipe_id' => 1, 'status' => 0, 'status_aprovacao' => 2]);
        $p79 = Projeto::create(['descricao' => 'VAANDROID-1', 'equipe_id' => 5, 'status' => 1, 'status_aprovacao' => 2]);
        $p80 = Projeto::create(['descricao' => 'ML-1288', 'equipe_id' => 1, 'status' => 1, 'status_aprovacao' => 2]);
        $p81 = Projeto::create(['descricao' => 'PAYFACE-1', 'equipe_id' => 1, 'status' => 1, 'status_aprovacao' => 2]);
        $p82 = Projeto::create(['descricao' => 'PROMOCONV-1', 'equipe_id' => 1, 'status' => 1, 'status_aprovacao' => 2]);
        $p83 = Projeto::create(['descricao' => 'CONSULPROD-1', 'equipe_id' => 4, 'status' => 1, 'status_aprovacao' => 2]);
        $p84 = Projeto::create(['descricao' => 'PROPZ-1', 'equipe_id' => 1, 'status' => 1, 'status_aprovacao' => 2]);
        $p85 = Projeto::create(['descricao' => 'DESIMPTEF-1', 'equipe_id' => 1, 'status' => 1, 'status_aprovacao' => 2]);
        $p86 = Projeto::create(['descricao' => 'UPLIFT-1', 'equipe_id' => 1, 'status' => 1, 'status_aprovacao' => 2]);
        $p87 = Projeto::create(['descricao' => 'PROMOAPP2-1', 'equipe_id' => 1, 'status' => 1, 'status_aprovacao' => 2]);
        $p88 = Projeto::create(['descricao' => 'INTPDVSAP-1', 'equipe_id' => 1, 'status' => 1, 'status_aprovacao' => 2]);
        $p89 = Projeto::create(['descricao' => 'PETINTKALU-1', 'equipe_id' => 1, 'status' => 2, 'status_aprovacao' => 2]);
        $p90 = Projeto::create(['descricao' => 'PARKPLUS-2', 'equipe_id' => 1, 'status' => 2, 'status_aprovacao' => 2]);
        $p91 = Projeto::create(['descricao' => 'SENHADIA-1', 'equipe_id' => 2, 'status' => 0, 'status_aprovacao' => 2]);
        $p92 = Projeto::create(['descricao' => 'TROCACPLJ-1', 'equipe_id' => 1, 'status' => 0, 'status_aprovacao' => 2]);
        $p93 = Projeto::create(['descricao' => 'SAIDAOPER-1', 'equipe_id' => 1, 'status' => 1, 'status_aprovacao' => 2]);
        $p94 = Projeto::create(['descricao' => 'MELHORIASAPP-1', 'equipe_id' => 5, 'status' => 0, 'status_aprovacao' => 2]);
        $p95 = Projeto::create(['descricao' => 'PAYFACEAPP-1', 'equipe_id' => 5, 'status' => 0, 'status_aprovacao' => 2]);
        $p96 = Projeto::create(['descricao' => 'MZCANCANT-1', 'equipe_id' => 1, 'status' => 0, 'status_aprovacao' => 2]);
        $p97 = Projeto::create(['descricao' => 'ACRESCITEM-1', 'equipe_id' => 1, 'status' => 1, 'status_aprovacao' => 3]);
        $p98 = Projeto::create(['descricao' => 'TROCASEMCV-1', 'equipe_id' => 1, 'status' => 1, 'status_aprovacao' => 3]);
        $p99 = Projeto::create(['descricao' => 'PGSOROCRED-1', 'equipe_id' => 1, 'status' => 1, 'status_aprovacao' => 3]);
        $p100 = Projeto::create(['descricao' => 'COBNEPOS-1', 'equipe_id' => 1, 'status' => 2, 'status_aprovacao' => 3]);
        $p101 = Projeto::create(['descricao' => 'PETENTREGA-1', 'equipe_id' => 1, 'status' => 1, 'status_aprovacao' => 3]);
        $p102 = Projeto::create(['descricao' => 'CRMONEID-1', 'equipe_id' => 1, 'status' => 0, 'status_aprovacao' => 1]);
        $p103 = Projeto::create(['descricao' => 'TENDENCIA-1', 'equipe_id' => 1, 'status' => 0, 'status_aprovacao' => 1]);
        $p104 = Projeto::create(['descricao' => 'FACTURAA4-1', 'equipe_id' => 1, 'status' => 0, 'status_aprovacao' => 1]);
        $p105 = Projeto::create(['descricao' => 'VALIDAEP-1', 'equipe_id' => 1, 'status' => 0, 'status_aprovacao' => 1]);
        $p106 = Projeto::create(['descricao' => 'SORTEIOFIN-1', 'equipe_id' => 1, 'status' => 0, 'status_aprovacao' => 1]);
        $p107 = Projeto::create(['descricao' => 'CADSORTEIO-1', 'equipe_id' => 1, 'status' => 0, 'status_aprovacao' => 1]);
        $p108 = Projeto::create(['descricao' => 'AUDITTROCA-1', 'equipe_id' => 1, 'status' => 0, 'status_aprovacao' => 1]);
        $p109 = Projeto::create(['descricao' => 'PERTO-1', 'equipe_id' => 1, 'status' => 0, 'status_aprovacao' => 1]);
        $p110 = Projeto::create(['descricao' => 'INTMELIUZ-1', 'equipe_id' => 1, 'status' => 1, 'status_aprovacao' => 1]);
        $p111 = Projeto::create(['descricao' => 'WEDOO-1', 'equipe_id' => 1, 'status' => 0, 'status_aprovacao' => 1]);
        $p112 = Projeto::create(['descricao' => 'NPSFASE6-1', 'equipe_id' => 1, 'status' => 0, 'status_aprovacao' => 1]);
        $p113 = Projeto::create(['descricao' => 'VPTELAPDV-1', 'equipe_id' => 1, 'status' => 0, 'status_aprovacao' => 1]);
        $p114 = Projeto::create(['descricao' => 'PROMOLISTA-1', 'equipe_id' => 1, 'status' => 0, 'status_aprovacao' => 1]);
        $p115 = Projeto::create(['descricao' => 'LOGVOUCHER-1', 'equipe_id' => 1, 'status' => 0, 'status_aprovacao' => 1]);
        $p116 = Projeto::create(['descricao' => 'APPDMCARD-1', 'equipe_id' => 1, 'status' => 0, 'status_aprovacao' => 1]);
        $p117 = Projeto::create(['descricao' => 'STOPBANK-1', 'equipe_id' => 1, 'status' => 0, 'status_aprovacao' => 1]);
        $p118 = Projeto::create(['descricao' => 'CUSTSPICY-1', 'equipe_id' => 1, 'status' => 0, 'status_aprovacao' => 1]);
        $p119 = Projeto::create(['descricao' => 'INTJOYA-1', 'equipe_id' => 1, 'status' => 0, 'status_aprovacao' => 1]);
        $p120 = Projeto::create(['descricao' => 'ORDEMSERV-1', 'equipe_id' => 1, 'status' => 0, 'status_aprovacao' => 2]);
        $p121 = Projeto::create(['descricao' => 'AJUSTNFCE-1', 'equipe_id' => 1, 'status' => 1, 'status_aprovacao' => 2]);
        $p122 = Projeto::create(['descricao' => 'ARREDONDAR-1', 'equipe_id' => 1, 'status' => 0, 'status_aprovacao' => 2]);
        $p123 = Projeto::create(['descricao' => 'CTRBLOCOX-1', 'equipe_id' => 1, 'status' => 0, 'status_aprovacao' => 2]);
        $p124 = Projeto::create(['descricao' => 'CRMSAC-1', 'equipe_id' => 1, 'status' => 0, 'status_aprovacao' => 2]);
        $p125 = Projeto::create(['descricao' => 'CRMPONTOS-1', 'equipe_id' => 1, 'status' => 0, 'status_aprovacao' => 2]);
        $p126 = Projeto::create(['descricao' => 'INTBOOME-1', 'equipe_id' => 1, 'status' => 0, 'status_aprovacao' => 0]);
        $p127 = Projeto::create(['descricao' => 'PROTHEUS2-1', 'equipe_id' => 1, 'status' => 0, 'status_aprovacao' => 0]);
        $p128 = Projeto::create(['descricao' => 'PETENTREGA2-1', 'equipe_id' => 1, 'status' => 0, 'status_aprovacao' => 0]);
        $p129 = Projeto::create(['descricao' => 'INTADYENF1-1', 'equipe_id' => 1, 'status' => 0, 'status_aprovacao' => 0]);
        $p130 = Projeto::create(['descricao' => 'CANCDEV-39', 'equipe_id' => 2, 'status' => 0, 'status_aprovacao' => 0]);
        $p131 = Projeto::create(['descricao' => 'LOPNOVGISS-1', 'equipe_id' => 1, 'status' => 0, 'status_aprovacao' => 0]);
        $p132 = Projeto::create(['descricao' => 'SINALSELF-1', 'equipe_id' => 1, 'status' => 0, 'status_aprovacao' => 0]);
        $p133 = Projeto::create(['descricao' => 'DEVITEMPR-1', 'equipe_id' => 1, 'status' => 0, 'status_aprovacao' => 0]);
        $p134 = Projeto::create(['descricao' => 'INTTODOCAR-1', 'equipe_id' => 1, 'status' => 0, 'status_aprovacao' => 0]);
        $p135 = Projeto::create(['descricao' => 'LISTADESC-1', 'equipe_id' => 1, 'status' => 0, 'status_aprovacao' => 0]);
        $p136 = Projeto::create(['descricao' => 'POMPEIA-1', 'equipe_id' => 1, 'status' => 0, 'status_aprovacao' => 0]);
        $p137 = Projeto::create(['descricao' => 'PRODCOMB-1', 'equipe_id' => 1, 'status' => 0, 'status_aprovacao' => 0]);
        $p138 = Projeto::create(['descricao' => 'POPUPMERC-1', 'equipe_id' => 1, 'status' => 0, 'status_aprovacao' => 0]);
        $p139 = Projeto::create(['descricao' => 'DOTZLGPD-1', 'equipe_id' => 1, 'status' => 0, 'status_aprovacao' => 0]);
        $p140 = Projeto::create(['descricao' => 'INTCATRACA-1', 'equipe_id' => 1, 'status' => 0, 'status_aprovacao' => 0]);
        $p141 = Projeto::create(['descricao' => 'NFECOMPLE-1', 'equipe_id' => 1, 'status' => 0, 'status_aprovacao' => 0]);
        $p142 = Projeto::create(['descricao' => 'CONFTURNO-1', 'equipe_id' => 1, 'status' => 0, 'status_aprovacao' => 0]);
        $p143 = Projeto::create(['descricao' => 'MERCAFACIL-1A', 'equipe_id' => 1, 'status' => 0, 'status_aprovacao' => 0]);
        $p144 = Projeto::create(['descricao' => 'MERCAFACIL-1B', 'equipe_id' => 1, 'status' => 0, 'status_aprovacao' => 0]);
        $p145 = Projeto::create(['descricao' => 'TOTAUTOSER-1', 'equipe_id' => 1, 'status' => 0, 'status_aprovacao' => 0]);
        $p146 = Projeto::create(['descricao' => 'PRDESCRAT-1', 'equipe_id' => 1, 'status' => 0, 'status_aprovacao' => 0]);
        $p147 = Projeto::create(['descricao' => 'TOTCONDUCT-1', 'equipe_id' => 1, 'status' => 0, 'status_aprovacao' => 0]);
        $p148 = Projeto::create(['descricao' => 'NFCEMODULO-1', 'equipe_id' => 1, 'status' => 0, 'status_aprovacao' => 0]);
        $p149 = Projeto::create(['descricao' => 'INTAPIPR-1', 'equipe_id' => 1, 'status' => 0, 'status_aprovacao' => 0]);
        $p150 = Projeto::create(['descricao' => 'CONTPESO-1', 'equipe_id' => 1, 'status' => 0, 'status_aprovacao' => 0]);
        $p151 = Projeto::create(['descricao' => 'DEVSEMCP-1', 'equipe_id' => 1, 'status' => 0, 'status_aprovacao' => 0]);
        $p152 = Projeto::create(['descricao' => 'QRCODEGPOS-1', 'equipe_id' => 1, 'status' => 0, 'status_aprovacao' => 0]);
        $p153 = Projeto::create(['descricao' => 'ZANVOUKERN-1', 'equipe_id' => 1, 'status' => 0, 'status_aprovacao' => 0]);
        $p154 = Projeto::create(['descricao' => 'ALTENTNF-1', 'equipe_id' => 1, 'status' => 0, 'status_aprovacao' => 0]);
        $p155 = Projeto::create(['descricao' => 'NEWBLOCOX-1', 'equipe_id' => 1, 'status' => 0, 'status_aprovacao' => 0]);
        $p156 = Projeto::create(['descricao' => 'ZANSATAJUS-1', 'equipe_id' => 1, 'status' => 0, 'status_aprovacao' => 0]);
        $p157 = Projeto::create(['descricao' => 'PCF2-1', 'equipe_id' => 1, 'status' => 0, 'status_aprovacao' => 0]);
        $p158 = Projeto::create(['descricao' => 'ZANINTDFIS-1', 'equipe_id' => 1, 'status' => 0, 'status_aprovacao' => 0]);
        $p159 = Projeto::create(['descricao' => 'ZANPROMFAC-1', 'equipe_id' => 1, 'status' => 0, 'status_aprovacao' => 0]);
        $p160 = Projeto::create(['descricao' => 'CANCDEV-1', 'equipe_id' => 1, 'status' => 0, 'status_aprovacao' => 0]);
        $p161 = Projeto::create(['descricao' => 'BLOQCAMPO-1', 'equipe_id' => 1, 'status' => 0, 'status_aprovacao' => 0]);
        $p162 = Projeto::create(['descricao' => 'CLOBLOJA-1', 'equipe_id' => 1, 'status' => 1, 'status_aprovacao' => 0]);
        $p163 = Projeto::create(['descricao' => 'CANCDEV-1', 'equipe_id' => 1, 'status' => 0, 'status_aprovacao' => 0]);


    }
}
